baseURL = 'https://reai.no/'
languageCode = 'nb-NO'
title = 'ReAI'
disableKinds = ["taxonomy", "term", "RSS"]
enableRobotsTXT = true
enableGitInfo = true # Use Git/file times for <lastmod> in pages and sitemap

[minify]
  minifyOutput = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'Komplett regnskapssystem med AI-drevet automatisering'
