baseURL = 'https://reai.no/'
languageCode = 'nb-no'
title = 'ReAI'

[permalinks]
  pages = '/pages/:filename/'
  products = '/products/:filename/'
  blogs = '/blog/:filename/'

# Enable redirects
[outputs]
  home = ['HTML', 'RSS', 'REDIRECTS']

[outputFormats]
  [outputFormats.REDIRECTS]
    mediaType = 'text/plain'
    baseName = '_redirects'
    notAlternative = true

[[redirects]]
  from = "/courses/*"
  to = "/collections/all/"
  status = 301

[[redirects]]
  from = "/fakturamal/*"
  to = "/pages/lag-faktura-gratis/"
  status = 301

[[redirects]]
  from = "/contact/*"
  to = "/pages/contact/"
  status = 301

[[redirects]]
  from = "/bli-partner/*"
  to = "/pages/bli-partner/"
  status = 301

[services]
  [services.robotsTXT]
    enable = true

[params]
  description = 'Komplett regnskapssystem med faktura, lønn, bilagsføring og årsoppgjør.'

# Use Git/file times for <lastmod> in pages and sitemap
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allow raw HTML, important for JSON-LD etc.
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[pagination]
  pagerSize = 6
