baseURL = 'http://localhost:1313/'
languageCode = 'no'
title = 'ReAI'

disableKinds = ["taxonomy", "term"]

[outputs]
  home = ['HTML', 'RSS']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'Komplett regnskapssystem med AI-drevet automatisering'
  theme_color = '#1e40af'
