baseURL = '/'
languageCode = 'nb-no'
title = 'ReAI'

enableRobotsTXT = true

[params]
  description = 'Komplett regnskapssystem med faktura, lønn, bilagsføring og årsoppgjør.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
  name = 'Produkter'
  url = '/products/'
  weight = 1

  [[menus.main]]
  name = 'Kurs og guider'
  url = '/courses/'
  weight = 2

  [[menus.main]]
  name = 'Blogg'
  url = '/blog/'
  weight = 3

  [[menus.main]]
  name = 'Kontakt oss'
  url = '/contact/'
  weight = 100

[pagination]
  pagerSize = 6
