baseURL = 'https://reai.no/'
languageCode = 'nb-NO'
title = 'ReAI'

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'Komplett regnskapssystem med AI-drevet automatisering'
